title: Threshold Trilogy
description: Anomalies, participation, and resonance
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  math_engine: mathjax  # Enables MathJax processing
  input: GFM
